# Generated by Django 3.2.2 on 2021-09-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210917_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_id', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='fcm_device',
            field=models.ForeignKey(db_column='fcm_device', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fcmdevice'),
        ),
    ]
