# Generated by Django 3.2.2 on 2021-09-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0007_alter_fcmdevice_id'),
        ('account', '0003_auto_20210918_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fcm_device',
            field=models.ForeignKey(db_column='fcm_device', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fcm_django.fcmdevice'),
        ),
        migrations.DeleteModel(
            name='FCMDevice',
        ),
    ]
