# Generated by Django 3.2.2 on 2021-09-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('drowsy', 'drowsy'), ('un authorized', 'un authorized'), ('distracted', 'distracted'), ('weapon', 'weapon')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('trip_id', models.CharField(default='trip_1', max_length=250)),
                ('alert_severity', models.FloatField(default=0.5)),
                ('alert_type', models.ForeignKey(db_column='alert_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.alerttype')),
            ],
        ),
    ]
