# Generated by Django 3.2.2 on 2021-09-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
