# Generated by Django 3.2.2 on 2021-09-18 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_alerts_resolved'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='driver',
            field=models.ForeignKey(db_column='driver', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TripPassengers',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('passenger', models.ForeignKey(db_column='passenger', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(db_column='trip', on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
            ],
        ),
        migrations.CreateModel(
            name='TripAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('alert', models.ForeignKey(db_column='alert', on_delete=django.db.models.deletion.CASCADE, to='alerts.alerts')),
                ('trip', models.ForeignKey(db_column='trip', on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('is_alert_valid', models.BooleanField(default=True)),
                ('passenger', models.ForeignKey(db_column='passenger', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip_alert', models.ForeignKey(db_column='trip_alert', on_delete=django.db.models.deletion.CASCADE, to='trips.tripalerts')),
            ],
        ),
    ]
